builds:
  - main: main.go
    binary: dbt-source-importer
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      386: i386
      amd64: x86_64
