# https://goreleaser.com/customization/builds/?h=mod#go-modules
before:
  hooks:
  - go mod tidy

builds:
  - main: main.go
    binary: dbt-source-importer
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
